services:
  traefik:
    image: docker.io/library/traefik:2.11.2
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker/traefik/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /home/ubuntu/docker/traefik/config/conf/:/etc/traefik/conf/
      - /home/ubuntu/docker/traefik/ssl:/etc/traefik/certs/

    restart: unless-stopped
