http:
  routers:
    your-local-router:
      rule: "Host(`portainer.ratne.it`) && PathPrefix(`/`)"
      service: your-local-service
      priority: 1000
      entryPoints:
        - web
        # (optional) Permanent Redirect to HTTPS
        # - websecure

  services:
    your-local-service:
      loadBalancer:
        servers:
          - url: "http://portainer.ratne.it:1234"
